### ISSUE TITLE
Update due date failed

### ISSUE THREAD

**Issue by rlindsberg** [rlindsberg/2207ID-SEP-Business-Management-System#7]
![Skærmbillede 2022-10-17 kl  20 20 02](https://user-images.githubusercontent.com/2918707/196252959-2efa1663-45f0-4810-8720-0759d7064365.png)

To replicate:
Run https://github.com/rlindsberg/2207ID-SEP-Business-Management-System/commit/858a8ada8da940d46ba3e1e8d88b7e8a7cd02704

Run the following in postman:
1. create request
2. create new event
3. create new subteam
4. create new task
5. update due date

**Comment by HaidaLu** [comment]
I have fixed the bug!
